/*
   This file has been generated by IDA.
   It contains local type definitions from
     /home/xvilka/RE/hw/asrockp4i65gv/asrockp4i65g.idb
*/

/*    1 */
enum CPU_MSRS
{
  IA32_TIME_STAMP_COUNTER = 0x10,
  IA32_PLATFORM_ID = 0x17,
  MSR_EBC_FREQUENCY_ID = 0x2C,
  IA32_BIOS_UPDT_TRIG = 0x79,
  IA32_BIOS_SIGN_ID = 0x8B,
  IA32_PERF_STATUS = 0x198,
  IA32_PERF_CTL = 0x199,
  IA32_MISC_ENABLE = 0x1A0,
  MSR_PLATFORM_BRV = 0x1A1,
  IA32_MTRR_PHYSBASE0 = 0x200,
  IA32_MTRR_PHYSMASK0 = 0x201,
  IA32_MTRR_PHYSMASK7 = 0x20F,
  IA32_MTRR_FIX64K_00000 = 0x250,
  IA32_MTRR_FIX16K_80000 = 0x258,
  IA32_MTRR_FIX16K_A0000 = 0x259,
  IA32_MTRR_FIX4K_C0000 = 0x268,
  IA32_MTRR_FIX4K_C8000 = 0x269,
  IA32_MTRR_FIX4K_D0000 = 0x26A,
  IA32_MTRR_FIX4K_D8000 = 0x26B,
  IA32_MTRR_FIX4K_E0000 = 0x26C,
  IA32_MTRR_FIX4K_E8000 = 0x26D,
  IA32_MTRR_FIX4K_F0000 = 0x26E,
  IA32_MTRR_FIX4K_F8000 = 0x26F,
  IA32_MTRR_DEF_TYPE = 0x2FF,
};

/*    2 */
enum SMBus
{
  SMBUS_HST_STS = 0x400,
  SMBUS_HST_CNT = 0x402,
  SMBUS_HST_CMD = 0x403,
  SMBUS_XMIT_SLVA = 0x404,
  SMBUS_HST_D0 = 0x405,
  SMBUS_HST_D1 = 0x406,
};

/*    3 */
struct PCI_reg_mask
{
  char reg_address;
  char disable_mask;
  char enable_mask;
};

/*    5 */
struct SMBus_reg
{
  char field_0;
  char field_1;
};

/*    6 */
struct PCI_reg_masks
{
  char pci_reg;
  short mask;
};

/*    7 */
enum GPIO_registers
{
  GPIO_USE_SEL = 0x480,
  GP_IO_SEL = 0x484,
  GP_LVL = 0x48C,
  GPO_TTL = 0x494,
  GPO_BLINK = 0x498,
  GPI_INV = 0x4AC,
  GPIO_USE_SEL2 = 0x4B0,
  GP_IO_SEL2 = 0x4B4,
  GP_LVL2 = 0x4B8,
};

/*    8 */
struct SIO_reg_mask
{
  char reg_address;
  char disable_mask;
  char enable_mask;
};

/*    9 */


/* End of file */
